language: node_js
node_js:
  - "0.10"
before_install:
  - "npm install -g browserify"
  - "npm install -g testling"
  - "npm install -g mocha"
  - "npm install -g bower"
  - "bower install"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
